"""initial schema: users, wallets, policies, transactions, activities

Revision ID: 61b2d8e30c95
Revises: 
Create Date: 2026-09-21 13:53:12.793743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b2d8e30c95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('risk_preference', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel', native_enum=False, length=16), server_default='MEDIUM', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('max_transaction_amount', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('daily_limit', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('allowed_protocols', sa.JSON(), nullable=False),
    sa.Column('allowed_actions', sa.JSON(), nullable=False),
    sa.Column('max_risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel', native_enum=False, length=16), server_default='MEDIUM', nullable=False),
    sa.Column('approval_required', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_user_id'), 'policies', ['user_id'], unique=True)
    op.create_table('wallets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('chain', sa.String(length=32), server_default='monad', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain', 'address', name='uq_wallets_chain_address')
    )
    op.create_index(op.f('ix_wallets_address'), 'wallets', ['address'], unique=False)
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('protocol', sa.String(length=64), nullable=False),
    sa.Column('token_in', sa.String(length=32), nullable=False),
    sa.Column('amount_in', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('token_out', sa.String(length=32), nullable=True),
    sa.Column('amount_out', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RISK_REJECTED', 'POLICY_REJECTED', 'AWAITING_APPROVAL', 'APPROVED', 'REJECTED_BY_USER', 'SUBMITTED', 'CONFIRMED', 'FAILED', name='transactionstatus', native_enum=False, length=32), server_default='PENDING', nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel', native_enum=False, length=16), nullable=True),
    sa.Column('risk_explanation', sa.JSON(), nullable=True),
    sa.Column('policy_decision', sa.JSON(), nullable=True),
    sa.Column('raw_ai_action', sa.JSON(), nullable=True),
    sa.Column('chain', sa.String(length=32), server_default='monad', nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_tx_hash'), 'transactions', ['tx_hash'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_transactions_wallet_id'), 'transactions', ['wallet_id'], unique=False)
    op.create_table('activities',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('TRANSACTION', 'PORTFOLIO_UPDATE', 'RECOMMENDATION', 'SYSTEM', name='activitytype', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('related_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('activity_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_related_transaction_id'), 'activities', ['related_transaction_id'], unique=False)
    op.create_index(op.f('ix_activities_type'), 'activities', ['type'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_type'), table_name='activities')
    op.drop_index(op.f('ix_activities_related_transaction_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_transactions_wallet_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_tx_hash'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_address'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_policies_user_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_table('users')
    # ### end Alembic commands ###
