"""add blockchain fields to transactions

Revision ID: 841cc9c51a8f
Revises: 61b2d8e30c95
Create Date: 2026-09-21 14:23:41.311867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841cc9c51a8f'
down_revision: Union[str, None] = '61b2d8e30c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('target_contract', sa.String(length=64), nullable=True))
    op.add_column('transactions', sa.Column('calldata', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('unsigned_tx', sa.JSON(), nullable=True))
    op.add_column('transactions', sa.Column('block_number', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'confirmed_at')
    op.drop_column('transactions', 'block_number')
    op.drop_column('transactions', 'unsigned_tx')
    op.drop_column('transactions', 'calldata')
    op.drop_column('transactions', 'target_contract')
    # ### end Alembic commands ###
